version: '3.4'
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fsms
    volumes:
      - postgres_sdata:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  adminer:
    image: adminer
    ports:
      - "8089:8080"

  smtp:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025:1025"
      - "8025:8025"


volumes:
  postgres_sdata: