CREATE TABLE addresses
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    district  VARCHAR(255)                            NOT NULL,
    locality  VARCHAR(255),
    latitude  FLOAT,
    longitude FLOAT,
    province  VARCHAR(255),
    CONSTRAINT pk_address PRIMARY KEY (id)
);


CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(63),
    phone      VARCHAR(15),
    user_role  VARCHAR(255),
    password   VARCHAR(63),
    name       VARCHAR(63),
    address_id BIGINT,
    CONSTRAINT pk_user PRIMARY KEY (id),
    UNIQUE (email),
    UNIQUE (phone),
    CONSTRAINT FK_USER_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES addresses (id)
);

CREATE TABLE blacklisted_tokens
(
    token      VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_blacklisted_tokens PRIMARY KEY (token)
);



CREATE TABLE chats
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    CONSTRAINT pk_chats PRIMARY KEY (id)
);

CREATE TABLE messages
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message    TEXT,
    chat_id    BIGINT,
    sent_by    BIGINT,
    seen_at    TIMESTAMP,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_messages PRIMARY KEY (id),
    FOREIGN KEY (chat_id) REFERENCES chats (id),
    FOREIGN KEY (sent_by) REFERENCES users (id)
);



CREATE TABLE posts
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR(255),
    body           TEXT,
    images         TEXT,
    visualizations BIGINT                      DEFAULT 0,
    user_id        BIGINT,
    created_at     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE post_comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment    TEXT,
    post_id    BIGINT,
    user_id    BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (id),
    FOREIGN KEY (post_id) REFERENCES posts (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);



CREATE TABLE chats_users
(
    user_id BIGINT,
    chat_id BIGINT,
    FOREIGN KEY (chat_id) REFERENCES chats (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE TABLE groups
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(63),
    chat_id    BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_groups PRIMARY KEY (id)
);



ALTER TABLE groups
    ADD CONSTRAINT FK_GROUPS_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chats (id);
CREATE TABLE users_groups
(
    groups_id BIGINT NOT NULL,
    user_id   BIGINT NOT NULL
);

ALTER TABLE users_groups
    ADD CONSTRAINT fk_usegro_on_group FOREIGN KEY (groups_id) REFERENCES groups (id);

ALTER TABLE users_groups
    ADD CONSTRAINT fk_usegro_on_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE posts
    ADD group_id BIGINT;