CREATE TABLE address
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    district  VARCHAR(255)                            NOT NULL,
    locality  VARCHAR(255),
    latitude  FLOAT,
    longitude FLOAT,
    province  VARCHAR(255),
    CONSTRAINT pk_address PRIMARY KEY (id)
);


CREATE TABLE "user"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(64),
    phone      VARCHAR(16),
    user_role  VARCHAR(255),
    password   VARCHAR(64),
    name       VARCHAR(64),
    address_id BIGINT,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_phone UNIQUE (phone);

ALTER TABLE "user"
    ADD CONSTRAINT FK_USER_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES address (id);