

CREATE TABLE if not exists roles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(64),
    icon VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

-- ALTER TABLE users
--     ADD if not exists CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES roles (id);
