CREATE TABLE addresses
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    district  VARCHAR(255)                            NOT NULL,
    locality  VARCHAR(255),
    latitude  FLOAT,
    longitude FLOAT,
    province  VARCHAR(255),
    CONSTRAINT pk_address PRIMARY KEY (id)
);


CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(64),
    phone      VARCHAR(16),
    user_role  VARCHAR(255),
    password   VARCHAR(64),
    name       VARCHAR(64),
    address_id BIGINT,
    CONSTRAINT pk_user PRIMARY KEY (id),
    UNIQUE(email, phone),
    CONSTRAINT FK_USER_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES addresses (id)
);

CREATE TABLE blacklisted_tokens
(
    token      VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_blacklisted_tokens PRIMARY KEY (token)
);